name: Deploy Node.js Application

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        always-auth: false
        check-latest: false
        token: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci  # Installs dependencies based on package-lock.json

    # Step 4: Build Docker image for Node.js application
    - name: Build Docker image
      run: docker build -t node-app .

    # Step 5: Stop and remove any old containers (if they exist)
    - name: Stop and remove old container
      run: |
        docker stop node-app || true
        docker rm node-app || true

    # Step 6: Run Docker container for Node.js app with MongoDB connection
    - name: Run Docker container for Node.js app
      run: |
        docker run -d --name node-app \
          -e MONGODB_URI=mongodb://152.42.193.252:27017/findatabase \
          -e DB_NAME=${{ secrets.DB_NAME }} \
          -e API_KEY=${{ secrets.API_KEY }} \
          -p 3000:3000 node-app

    # Step 7: Check the status of the running containers
    - name: Check running containers
      run: docker ps

    # Step 8: Capture logs if the job fails
    - name: Capture logs
      if: failure()
      run: docker logs node-app